//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTM.Net.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTM.Net.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timestamp,consumption
        ///datetime,float
        ///T,,R
        ///7/2/10 0:00,21.2,0
        ///7/2/10 1:00,16.4,0
        ///7/2/10 2:00,4.7,0
        ///7/2/10 3:00,4.7,0
        ///7/2/10 4:00,4.6,0
        ///7/2/10 5:00,23.5,0
        ///7/2/10 6:00,47.5,0
        ///7/2/10 7:00,45.4,0
        ///7/2/10 8:00,46.1,0
        ///7/2/10 9:00,41.5,0
        ///7/2/10 10:00,43.4,0
        ///7/2/10 11:00,43.8,0
        ///7/2/10 12:00,37.8,0
        ///7/2/10 13:00,36.6,0
        ///7/2/10 14:00,35.7,0
        ///7/2/10 15:00,38.9,0
        ///7/2/10 16:00,36.2,0
        ///7/2/10 17:00,36.6,0
        ///7/2/10 18:00,37.2,0
        ///7/2/10 19:00,38.2,0
        ///7/2/10 20:00,14.1,0
        ///7/2/10 21:00,5.1,0
        ///7/2/10 22:00,5,0
        ///7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rec_center_hourly_4reset {
            get {
                return ResourceManager.GetString("rec_center_hourly_4reset", resourceCulture);
            }
        }
    }
}
